services:
  mediafetch:
    image: lukedunsmoto/mediafetch:1.2.0
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./downloads:/data/downloads
    environment:
      - PORT=${PORT}
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}

      - OUTPUT_DIR=/data/downloads




