services:
  mediafetch:
    build: .
    container_name: mediafetch
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      - ./downloads:/data/downloads
    environment:
      - PORT=${PORT}
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}

      - OUTPUT_DIR=${OUTPUT_DIR}
